apiVersion: v1
kind: Pod
metadata:
  name: egress-1
  labels:
    name: egress-1
  annotations:
    pod.network.openshift.io/assign-macvlan: "true" 
spec:
  containers:
  - name: egress-router
    image: registry.access.redhat.com/openshift3/ose-egress-router
    securityContext:
      privileged: true
    env:
    - name: EGRESS_SOURCE 
      value: 192.168.180.190
    - name: EGRESS_GATEWAY 
      value: 192.168.180.2
    - name: EGRESS_DESTINATION 
      value: 192.168.14.190
  nodeSelector:
    site: postgresql-marinet